version: "3.9"
services: 
  app:
    container_name: log-search-front
    image: node:12.18.1-alpine
    tty: true
    env_file:
      - .env
    ports: 
      - 8000:8080
    working_dir: /app
    volumes:
      - ./:/app 
