version: "3.9"
services: 
  app:
    build:
      context: .
      args:
        USER_UID: $DEV_UID
        USER_GID: $DEV_GID
    user: ${DEV_UID}:${DEV_GID}
    tty: true
    env_file:
      - .env
    ports: 
      - 7654:8080
    volumes:
      - ./:/app 
      - excluded:/app/node_modules
volumes:
  excluded: